DROP TABLE IF EXISTS LINE_STATISTIC;
CREATE TABLE LINE_STATISTIC
(
	ID_LINE			INT AUTO_INCREMENT,
	PRIMARY KEY (ID_LINE),
	ID_FILE			INT,
	LONGEST_WORD	INT,
	SHORTEST_WORD	INT,
	AVG_WORD		INT,
	LINE_LENGTH		INT,
	FOREIGN KEY (ID_FILE) REFERENCES FILE_STATISTIC (ID_FILE),
);