DROP TABLE IF EXISTS FILE_STATISTIC;
CREATE TABLE FILE_STATISTIC
(
	ID_FILE                INT AUTO_INCREMENT,
	PRIMARY KEY (ID_FILE),
	LONGEST_FILE_WORD      INT,
	SHORTEST_FILE_WORD     INT,
	AVG_FILE_WORD          INT,
	AVG_LINE_LENGTH        INT
);