DELETE FROM FILE_STATISTIC;
INSERT INTO FILE_STATISTIC (LONGEST_FILE_WORD, SHORTEST_FILE_WORD, AVG_FILE_WORD, AVG_LINE_LENGTH) VALUES (11,1,5,66);
INSERT INTO FILE_STATISTIC (LONGEST_FILE_WORD, SHORTEST_FILE_WORD, AVG_FILE_WORD, AVG_LINE_LENGTH) VALUES (9,2,4,65);
INSERT INTO FILE_STATISTIC (LONGEST_FILE_WORD, SHORTEST_FILE_WORD, AVG_FILE_WORD, AVG_LINE_LENGTH) VALUES (8,1,4,68);